author: Michel Anderson Lutz Teixeira
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLStarRating
root_url: https://micheltlutz.github.io/MLStarRating/
module: MLStarRating
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLStarRating.xcworkspace', -scheme, 'MLStarRating-iOS']
